import React,{useMemo,useState} from 'react';
import {NavLink,Navigate,Route,Routes,useLocation,useNavigate} from 'react-router-dom';
import {LayoutDashboard,Scale,Video,Clock3,WalletCards,CreditCard,HandCoins,Percent,History,MessageSquareWarning,RotateCcw,Star,ChartNoAxesCombined,Menu,X,Bell,Search,Plus,Download,Eye,Check,ChevronRight,LogOut} from 'lucide-react';
import {lawyers,transactions,payouts,complaints,reviews} from './data.js';
import {ConsultationOps} from './ConsultationOps.jsx';

const menu=[
 ['dashboard','Main Dashboard',LayoutDashboard],['consultations','Live Consultation',Video],['billing','Per-Minute Billing',Clock3],['wallet','Wallet Management',WalletCards],['payments','Payment Management',CreditCard],['payouts','Lawyer Payouts',HandCoins],['commissions','Commission Management',Percent],['history','Consultation History',History],['complaints','Complaints & Disputes',MessageSquareWarning],['refunds','Refund & Cancellation Rules',RotateCcw],['reviews','Ratings & Reviews',Star],['analytics','Reports & Analytics',ChartNoAxesCombined]
];
const stat=(label,value,trend='↗ 8.2% this month')=>({label,value,trend});

function Login(){const nav=useNavigate();const [register,setRegister]=useState(false);const [error,setError]=useState('');function submit(e){e.preventDefault();const form=new FormData(e.currentTarget);if(!form.get('email')||!form.get('password'))return setError('Please complete all required fields.');localStorage.setItem('vakilReactSession',JSON.stringify({email:form.get('email'),name:form.get('name')||'Admin User'}));nav('/dashboard')}return <div className="auth-page"><section className="auth-art"><div className="art-logo"><Scale/> VAKIL</div><div><span>ENTERPRISE CONTROL</span><h1>Secure Admin<br/>Platform</h1><p>Enterprise-grade access management for legal platform administrators.</p></div></section><section className="auth-box"><form onSubmit={submit}><h2>{register?'Admin Registration':'Admin Access'}</h2><p>{register?'Create your administrator identity credential.':'Sign in to manage your platform resources.'}</p><div className="auth-tabs"><button type="button" className={!register?'active':''} onClick={()=>setRegister(false)}>Sign in</button><button type="button" className={register?'active':''} onClick={()=>setRegister(true)}>New registration</button></div>{register&&<label>Full name<input name="name" placeholder="Audrey Chen" required/></label>}<label>Work email<input name="email" type="email" defaultValue={!register?'admin@enterprise.com':''} required/></label><label>Password<input name="password" type="password" defaultValue={!register?'SecureAdmin12!':''} minLength="8" required/></label>{register&&<label>Role<select name="role"><option>Security Admin</option><option>Finance Manager</option><option>Customer Support</option></select></label>}{!register&&<label>Authentication code<input name="otp" defaultValue="824910" inputMode="numeric" maxLength="6" required/></label>}<small className="form-error">{error}</small><button className="primary wide">{register?'Create Admin Account':'Verify & Sign In'} <ChevronRight size={15}/></button></form></section></div>}

function Shell(){const [open,setOpen]=useState(false);const [profile,setProfile]=useState(false);const loc=useLocation();const nav=useNavigate();const current=menu.find(([path])=>loc.pathname.includes(path))?.[1]||'Dashboard';function logout(){localStorage.removeItem('vakilReactSession');nav('/login')}return <div className="shell"><aside className={open?'open':''}><div className="side-logo"><span><Scale size={16}/></span><div><b>Vakil Admin</b><small>CONTROL CENTER</small></div><button onClick={()=>setOpen(false)}><X/></button></div><nav>{menu.map(([path,label,Icon])=><NavLink key={path} to={'/'+path} onClick={()=>setOpen(false)}><Icon size={15}/><span>{label}</span></NavLink>)}</nav></aside><div className="workspace"><header><button className="hamburger" onClick={()=>setOpen(true)}><Menu/></button><b className="product">▣ LegalDash</b><div className="head-right"><button className="icon-btn" onClick={()=>alert('3 billing alerts require your attention.')}><Bell size={17}/><i/></button><div className="profile"><button onClick={()=>setProfile(!profile)}><span className="avatar">AU</span><span><b>Admin User</b><small>Super Admin</small></span></button>{profile&&<div className="profile-menu"><b>{current}</b><button onClick={logout}><LogOut size={14}/> Sign out</button></div>}</div></div></header><main><Routes><Route path="dashboard" element={<Dashboard/>}/><Route path="consultations" element={<Consultations/>}/><Route path="billing" element={<Billing/>}/><Route path="wallet" element={<Wallet/>}/><Route path="payments" element={<Payments/>}/><Route path="payouts" element={<Payouts/>}/><Route path="commissions" element={<Commissions/>}/><Route path="history" element={<ConsultationHistory/>}/><Route path="complaints" element={<Complaints/>}/><Route path="refunds" element={<Refunds/>}/><Route path="reviews" element={<Reviews/>}/><Route path="analytics" element={<Analytics/>}/><Route path="*" element={<Navigate to="/dashboard"/>}/></Routes></main></div></div>}

function PageHead({title,desc,action='Export Report',onAction}){return <div className="page-head"><div><h1>{title}</h1><p>{desc}</p></div><button className="primary" onClick={onAction||(()=>alert(`${action} started successfully.`))}>{action.includes('Export')?<Download size={14}/>:<Plus size={14}/>} {action}</button></div>}
function Stats({items}){return <div className="stats">{items.map((s,i)=><article className="stat" key={s.label}><div><span>{s.label}</span><i className={'dot c'+i}/></div><strong>{s.value}</strong><small className={s.trend.includes('↓')?'negative':''}>{s.trend}</small></article>)}</div>}
function Badge({children}){const bad=/Failed|Flagged|High|Overdue|Rejected/i.test(children),warn=/Pending|Waiting|Hold|Review|Processing/i.test(children);return <span className={'badge '+(bad?'bad':warn?'warn':'good')}>{children}</span>}
function DataTable({title,subtitle,rows,columns,filters=true}){const [query,setQuery]=useState('');const filtered=useMemo(()=>rows.filter(r=>Object.values(r).join(' ').toLowerCase().includes(query.toLowerCase())),[rows,query]);return <section className="card"><div className="card-head"><div><h3>{title}</h3><p>{subtitle}</p></div>{filters&&<div className="filters"><label><Search size={13}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search records..."/></label><select><option>All statuses</option><option>Completed</option><option>Pending</option><option>Failed</option></select></div>}</div><div className="table-wrap"><table><thead><tr>{columns.map(c=><th key={c.key}>{c.label}</th>)}<th>Actions</th></tr></thead><tbody>{filtered.map((row,i)=><tr key={row.id||row.name||i}>{columns.map(c=><td key={c.key}>{c.render?c.render(row[c.key],row):row[c.key]}</td>)}<td><button className="view" onClick={()=>alert(`Opening details for ${row.id||row.name}`)}><Eye size={13}/> View</button></td></tr>)}</tbody></table>{!filtered.length&&<div className="no-results">No matching records found.</div>}</div></section>}
const basicCols=[{key:'name',label:'Lawyer',render:(v,r)=><Person name={v} sub={r.email}/>},{key:'client',label:'Client'},{key:'type',label:'Category'},{key:'rate',label:'Rate'},{key:'duration',label:'Duration'},{key:'status',label:'Status',render:v=><Badge>{v}</Badge>}];
function Person({name,sub}){return <div className="person"><span className="avatar light">{name.split(' ').map(x=>x[0]).join('').slice(0,2)}</span><span><b>{name}</b><small>{sub}</small></span></div>}

function Dashboard(){return <><PageHead title="Main Dashboard" desc="A live overview of your legal services platform."/><Stats items={[stat('Active Consultations','08'),stat('Minutes Billed Today','14,250 Mins'),stat('Wallet Balance','₹89,40,500'),stat('Pending Complaints','24','↓ 3 require attention')]}/><div className="two-col"><MiniChart/><section className="card"><div className="card-head"><h3>Operational flow</h3></div><div className="flow">{['Client requests consultation','Lawyer accepts','Per-minute billing starts','Payment captured','Lawyer payout queued'].map((x,i)=><React.Fragment key={x}><div><span>{i+1}</span><b>{x}</b></div>{i<4&&<ChevronRight/>}</React.Fragment>)}</div></section></div><DataTable title="Recent Consultations" subtitle="Latest consultation activity across the platform." rows={lawyers} columns={basicCols}/></>}
function Consultations(){return <><PageHead title="Request & Live Consultation Management" desc="Monitor every request and ongoing session in real time." action="Monitor Queue"/><ConsultationOps/><Info text="Every lifecycle transition is captured in the request timeline."/></>}
function Billing(){return <><PageHead title="Per-Minute Billing System" desc="Configure time tracking, billing intervals, rate rules, safety controls, and reconciliation." action="Billing Preferences"/><Stats items={[stat('Minutes Billed Today','14,250 Mins'),stat('Adjustments & Claims','3 Session Adjusts'),stat('Live Revenue Billing','₹12,450.00')]}/><section className="card"><div className="card-head"><h3>Billing Flow Specification</h3><button className="link-btn">Save settings</button></div><div className="rule-grid">{['Countdown before billing','Session clock starts','Per-minute billing increments','Low balance warning','Idle session timeout','Automatic reconciliation'].map((x,i)=><div className="rule" key={x}><span>{i+1}</span><b>{x}</b><p>{['5 second countdown before the payable session begins.','Timer starts after both users connect.','Charge is calculated using the approved lawyer rate.','Customer is alerted before wallet exhaustion.','Session pauses after 60 seconds of inactivity.','Final amount is validated against the session log.'][i]}</p><button onClick={()=>alert(`${x} setting opened`)}>Configure</button></div>)}</div></section><DataTable title="Live Metering & Financial Exception Log" subtitle="Review recent automatic adjustments and billing exceptions." rows={transactions} columns={transactionCols}/></>}
const transactionCols=[{key:'id',label:'Transaction ID'},{key:'date',label:'Date'},{key:'customer',label:'Customer'},{key:'amount',label:'Amount'},{key:'method',label:'Payment Method'},{key:'status',label:'Status',render:v=><Badge>{v}</Badge>}];
function Wallet(){return <><PageHead title="Wallet Management" desc="Review customer and lawyer wallets, ledgers, balances, holds, and settlement activity."/><Info text="Ledger values are calculated from immutable transaction records and reconciled automatically."/><Stats items={[stat('Customer Wallet Balance','₹89,40,500'),stat('Customer Funds on Hold','₹12,40,000','↓ 4 disputes'),stat('Lawyer Wallet Balance','₹6,12,90,000'),stat('Available for Withdrawal','₹4,21,330')]}/><DataTable title="Customer Wallet Detail" subtitle="Balance, held amounts, credits, debits, and latest activity." rows={transactions} columns={transactionCols}/><DataTable title="Lawyer Wallet Detail" subtitle="Earnings and settlement history." rows={payouts} columns={payoutCols}/></>}
function Payments(){return <><PageHead title="Payment Management" desc="Monitor payment success, failures, refunds, reconciliation, and gateway performance." action="Run Reconciliation"/><div className="segmented"><button className="active">All Payments</button><button>Cards</button><button>Net Banking</button><button>Wallets</button><button>Refunds</button></div><Stats items={[stat('Active Payment Providers','5 Methods'),stat('Completed Payments','8,420 Payments'),stat('Pending Payments','128 Pending'),stat('Payment Issues Logged','24 Issues','↓ 8 unresolved')]}/><DataTable title="Transaction List" subtitle="Payment gateway activity and reconciliation status." rows={transactions} columns={transactionCols}/></>}
const payoutCols=[{key:'id',label:'Payout ID'},{key:'name',label:'Lawyer',render:(v,r)=><Person name={v} sub={r.role}/>},{key:'amount',label:'Amount'},{key:'status',label:'Status',render:v=><Badge>{v}</Badge>}];
function Payouts(){return <><PageHead title="Lawyer Payout Management" desc="Review, verify, schedule, hold, and release lawyer settlement payments." action="Process Pending Payouts"/><Stats items={[stat('Pending payout queue','₹4,28,500.00'),stat('Automatic weekly payout','Every Friday'),stat('Minimum withdrawal','₹2,500.00'),stat('Holds and review','3 / 2','↓ 2 compliance holds')]}/><section className="card payout-control"><h3>Settlement policy & payout controls</h3><p>Automatic payouts are processed each Friday after account and tax verification.</p><div><button className="primary" onClick={()=>alert('Weekly payout run scheduled')}>Run weekly payout</button><button className="secondary">View bank verification</button></div></section><DataTable title="Pending payout requests" subtitle="Approve or hold lawyer payout requests." rows={payouts} columns={payoutCols}/></>}
function Commissions(){return <><PageHead title="Commission Management" desc="Configure platform commission slabs, overrides, promotional rates, and payout deductions." action="Save Changes"/><Stats items={[stat('Default Platform Commission','20% Flat'),stat('Lawyer Overrides','12 Overrides'),stat('Rate Plans','18 Active'),stat('Commission Campaigns','3 Campaigns')]}/><section className="card"><div className="card-head"><h3>Commission configuration</h3></div><div className="commission-grid">{[['Default platform commission','20%'],['Premium lawyer rate','15% - 30%'],['Tiered matrix','Volume based'],['Promotional commission','15%'],['Tax applicability','As applicable'],['Effective date','01 Mar 2026']].map(([a,b])=><label key={a}>{a}<input defaultValue={b}/><small>Changes are logged and require administrator approval.</small></label>)}</div></section></>}
function ConsultationHistory(){return <><PageHead title="Consultation History" desc="Filter and review past consultation records, payments, ratings, and disputes."/><Stats items={[stat('Total Consultations','14,250'),stat('Completed Sessions','13,811'),stat('Net Amount','₹51,240'),stat('Disputed Sessions','42','↓ 12 need action')]}/><section className="card filter-panel"><h3>Advanced Filters</h3><div>{['Customer ID','Customer','Lawyer','Consultation Type','Date From','Date To'].map(x=><label key={x}>{x}<input placeholder={`Filter by ${x.toLowerCase()}`}/></label>)}<button className="primary">Apply Filters</button></div></section><DataTable title="Consultation Records" subtitle="Complete billing and consultation audit records." rows={lawyers} columns={basicCols}/></>}
const complaintCols=[{key:'id',label:'Ticket ID'},{key:'date',label:'Date Filed'},{key:'customer',label:'Customer'},{key:'lawyer',label:'Against Lawyer'},{key:'category',label:'Category'},{key:'status',label:'Status',render:v=><Badge>{v}</Badge>}];
function Complaints(){return <><PageHead title="Complaints & Dispute Management" desc="Monitor tickets, resolve complaints, assign cases, and review escalation workflows."/><Stats items={[stat('Total Complaints','342'),stat('Open','24','↓ 4 overdue'),stat('In Progress','89'),stat('Escalated','12','↓ Action required'),stat('Resolved','217')]}/><DataTable title="Complaint tickets" subtitle="Search complaints by customer, lawyer, or ticket ID." rows={complaints} columns={complaintCols}/></>}
function Refunds(){const [rules,setRules]=useState([true,true,true,true,true,true]);return <><PageHead title="Refund & Cancellation Rules" desc="Configure refund policies and cancellation rules for consultation flows." action="Save Changes"/><section className="card"><div className="card-head"><h3>Refund Scenarios</h3></div>{['Lawyer no-show','Lawyer ends session unexpectedly','Customer cancels before acceptance','Call disconnects immediately','Customer cancels after connection','Technical error'].map((x,i)=><div className="policy" key={x}><div><b>{x}</b><p>{['100% refund if the lawyer fails to join.','Credit unused minutes to customer wallet.','Full refund automatically.','Auto-refund within two minutes.','Charge only consumed minutes.','Automatic refund after log validation.'][i]}</p></div><Badge>{i===4?'Proportional Refund':'Full Refund'}</Badge><button className={'toggle '+(rules[i]?'on':'')} onClick={()=>setRules(r=>r.map((v,n)=>n===i?!v:v))}><i/></button></div>)}</section><div className="rule-grid">{['Lawyer-Based Refunds','Automatic vs Manual','Partial Refund Calculation'].map(x=><div className="card" key={x}><h3>{x}</h3><p>Configure a protected workflow with administrative audit controls.</p><button className="link-btn">Edit policy</button></div>)}</div></>}
function Reviews(){const cols=[{key:'name',label:'Customer',render:v=><Person name={v} sub="Verified customer"/>},{key:'lawyer',label:'Lawyer'},{key:'rating',label:'Rating',render:v=><span className="stars">{v}</span>},{key:'message',label:'Review Message'},{key:'status',label:'Status',render:v=><Badge>{v}</Badge>}];return <><PageHead title="Ratings & Reviews Moderation" desc="Audit client feedback, manage ratings, flag violations, and control lawyer reputation transparency."/><Stats items={[stat('Total Reviews','18,420'),stat('Average Rating','4.6 / 5.0'),stat('Pending Review','23','↓ 5 urgent'),stat('Flagged for Action','8','↓ Review required')]}/><DataTable title="Recent Feedback & Ratings" subtitle="Moderate published and flagged customer reviews." rows={reviews} columns={cols}/><MiniChart/></>}
function Analytics(){return <><PageHead title="Reports & Analytics Workspace" desc="Analyze business performance, revenue, consultations, and category metrics."/><Stats items={[stat('Daily Revenue','₹3,45,000'),stat('Monthly Revenue','₹1,02,50,000'),stat('Platform Commission','₹20,50,000'),stat('Refunds Processed','₹1,85,000','↓ 5.8% of revenue')]}/><MiniChart/><div className="two-col"><DataTable title="Top Performing Advocates" subtitle="By revenue and consultation volume." rows={payouts} columns={payoutCols} filters={false}/><section className="card"><div className="card-head"><h3>Category Demand</h3></div>{[['Family Law',85],['Corporate & Commercial',77],['Criminal Defense',61],['Civil Litigation',54],['Other',38]].map(([x,n])=><div className="progress" key={x}><span>{x}<b>{n}%</b></span><i><b style={{width:n+'%'}}/></i></div>)}</section></div></>}
function MiniChart(){
 const revenue=[36,31,43,38,55,49,46,62,58,69,64,75,68,82,71,76,89,80,84,93,87,99,91,104,108,95,110,114,118,121];
 const [range,setRange]=useState(30);const [active,setActive]=useState(revenue.length-1);const visible=revenue.slice(-range);const offset=revenue.length-visible.length;
 const selected=revenue[active];const change=active?((selected-revenue[active-1])/revenue[active-1]*100):0;
 return <section className="card chart interactive-chart"><div className="card-head"><div><h3>30-Day Revenue Trend</h3><p>Daily settled platform revenue · select any bar to inspect it</p></div><div className="range-tabs" aria-label="Chart date range">{[7,14,30].map(n=><button key={n} className={range===n?'active':''} onClick={()=>{setRange(n);setActive(revenue.length-1)}}>{n}D</button>)}</div></div><div className="chart-summary" aria-live="polite"><div><span>Oct {String(active+1).padStart(2,'0')}, 2026</span><strong>₹{(selected*1250).toLocaleString('en-IN')}</strong></div><Badge>{change>=0?`↑ ${change.toFixed(1)}%`:`↓ ${Math.abs(change).toFixed(1)}%`}</Badge></div><div className="bars" role="list" aria-label={`${range} day revenue chart`}>{visible.map((n,i)=>{const realIndex=offset+i;const amount=n*1250;return <button key={realIndex} role="listitem" className={active===realIndex?'selected':''} style={{height:n*.9}} onClick={()=>setActive(realIndex)} onMouseEnter={()=>setActive(realIndex)} onFocus={()=>setActive(realIndex)} aria-label={`October ${realIndex+1}: ₹${amount.toLocaleString('en-IN')}`}><span className="chart-tip">Oct {realIndex+1}<b>₹{amount.toLocaleString('en-IN')}</b></span></button>})}</div><div className="chart-axis"><span>Oct {offset+1}</span><span>Oct {offset+Math.ceil(visible.length/2)}</span><span>Oct 30</span></div></section>
}
function Info({text}){return <div className="info">ⓘ {text}</div>}
export default function App(){return <Routes><Route path="/login" element={<Login/>}/><Route path="/*" element={<Shell/>}/></Routes>}
