import React,{useEffect,useMemo,useState} from 'react';
import {io} from 'socket.io-client';
import {api,baseUrl,token} from './api.js';
const fmt=v=>v?new Date(v).toLocaleString():'—';
export function ConsultationOps({liveOnly=false}){
 const [items,setItems]=useState([]),[selected,setSelected]=useState(null),[timeline,setTimeline]=useState([]),[query,setQuery]=useState(''),[status,setStatus]=useState('');
 async function load(){const data=await api(liveOnly?'/api/admin/live':`/api/consultations?limit=100${status?`&status=${status}`:''}`);setItems(data.items)}
 useEffect(()=>{let socket;load().then(()=>{socket=io(baseUrl,{auth:{token:token()}});socket.on('status_updated',()=>load().catch(console.error))}).catch(console.error);return()=>socket?.disconnect()},[liveOnly,status]);
 async function detail(id){const data=await api(`/api/consultations/${id}`);setSelected(data.request);setTimeline(data.timeline)}
 const shown=useMemo(()=>items.filter(x=>JSON.stringify(x).toLowerCase().includes(query.toLowerCase())),[items,query]);
 return <><section className="card"><div className="card-head"><div><h3>{liveOnly?'Currently ongoing sessions':'Consultation requests'}</h3><p>Live data from the consultation service.</p></div><div className="filters"><label><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search requests"/></label>{!liveOnly&&<select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option>{['PENDING','ACCEPTED','ONGOING','COMPLETED','REJECTED','EXPIRED','CANCELLED'].map(x=><option key={x}>{x}</option>)}</select>}</div></div><div className="table-wrap"><table><thead><tr>{['ID','User','Lawyer','Category','Type','Status','Created','Response','Duration','Amount','Rating',''].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{shown.map(r=><tr key={r.id}><td>{r.id.slice(-8)}</td><td>{r.userName}</td><td>{r.lawyerName}</td><td>{r.category}</td><td>{r.consultationType}</td><td><span className="badge good">{r.status}</span></td><td>{fmt(r.createdAt)}</td><td>{r.acceptedAt?`${Math.round((new Date(r.acceptedAt)-new Date(r.createdAt))/1000)}s`:'—'}</td><td>{r.durationSeconds?`${r.durationSeconds}s`:'—'}</td><td>{r.amount??'—'}</td><td>{r.rating??'—'}</td><td><button className="view" onClick={()=>detail(r.id)}>View</button></td></tr>)}</tbody></table></div></section>{selected&&<section className="card"><div className="card-head"><div><h3>Request {selected.id}</h3><p>{selected.description||'No issue description supplied.'}</p></div><button className="secondary" onClick={()=>setSelected(null)}>Close</button></div><div className="timeline">{timeline.map(log=><div key={log.id}><b>{log.to}</b><span>{fmt(log.createdAt)} · {log.actorRole}</span></div>)}</div></section>}</>
}
